-- Capture run of script in file called mau_schema_output.txt
set echo on
SPOOL mau_schema_output.txt

-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-17 16:39:19 AEDT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--   name:      Ethan Neyland

DROP TABLE address CASCADE CONSTRAINTS;

DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artmedia_art CASCADE CONSTRAINTS;

DROP TABLE artstyle_art CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE artwork_media CASCADE CONSTRAINTS;

DROP TABLE artwork_status CASCADE CONSTRAINTS;

DROP TABLE artwork_style CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE exhibit CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE sale CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE address (
    address_id       NUMBER(7) NOT NULL,
    address_number   VARCHAR2(20 CHAR) NOT NULL,
    address_street   VARCHAR2(50 CHAR) NOT NULL,
    address_city     VARCHAR2(50 CHAR) NOT NULL,
    address_state    VARCHAR2(3 CHAR) NOT NULL,
    address_postcode CHAR(4 CHAR) NOT NULL
);

ALTER TABLE address
    ADD CHECK ( address_state IN ( 'ACT', 'NSW', 'NT', 'QLD', 'SA',
                                   'TAS', 'VIC', 'WA' ) );

COMMENT ON COLUMN address.address_id IS
    'Address ID Number';

COMMENT ON COLUMN address.address_number IS
    'Address House/Property Number of Street Address.
     Can contain numbers, letters, special characters.
     E.g.  U5/12 123-125 (Thomsons Road)';

COMMENT ON COLUMN address.address_street IS
    'Address Street Name and Street Type, e.g. Thomson Avenue ';

COMMENT ON COLUMN address.address_city IS
    'Address City/Town/Suburb Name, respective to provided postcode';

COMMENT ON COLUMN address.address_state IS
    'Address State within AUSTRALIA, 2-3 Chars representing full-name. 
     States: VIC, TAS, SA, WA, NT, QLD, ACT.';

COMMENT ON COLUMN address.address_postcode IS
    'Address Postcode (4 numeric chars) e.g. 3095';

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( address_id );

CREATE TABLE artist (
    artist_id             NUMBER(7) NOT NULL,
    artist_givname        VARCHAR2(50 CHAR) NOT NULL,
    artist_famname        VARCHAR2(50 CHAR) NOT NULL,
    artist_phone          CHAR(10 CHAR),
    artist_total_stock    NUMBER(3),
    artist_recommended_by NUMBER(7),
    address_id            NUMBER(7) NOT NULL
);

COMMENT ON COLUMN artist.artist_id IS
    'Artist ID Number';

COMMENT ON COLUMN artist.artist_givname IS
    'Artist First Name';

COMMENT ON COLUMN artist.artist_famname IS
    'Artist Family/Last Name';

COMMENT ON COLUMN artist.artist_phone IS
    'Artist Phone Number (optional)
     Requires 10 Numeric Chars';

COMMENT ON COLUMN artist.artist_total_stock IS
    'Artist''s Total no. of Artwork in MAU Stock';

COMMENT ON COLUMN artist.artist_recommended_by IS
    'Artist ID Number';

COMMENT ON COLUMN artist.address_id IS
    'Address ID Number';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_id );

CREATE TABLE artmedia_art (
    artmedia_id NUMBER(3) NOT NULL,
    artwork_id  NUMBER(7) NOT NULL
);

ALTER TABLE artmedia_art ADD CONSTRAINT artmedia_art_pk PRIMARY KEY ( artmedia_id,
                                                                      artwork_id );

CREATE TABLE artstyle_art (
    artstyle_id NUMBER(3) NOT NULL,
    artwork_id  NUMBER(7) NOT NULL
);

ALTER TABLE artstyle_art ADD CONSTRAINT artstyle_art_pk PRIMARY KEY ( artstyle_id,
                                                                      artwork_id );

CREATE TABLE artwork (
    artwork_id            NUMBER(7) NOT NULL,
    artist_id             NUMBER(7) NOT NULL,
    artwork_no            NUMBER(3) NOT NULL,
    artwork_title         VARCHAR2(100 CHAR) NOT NULL,
    artwork_date_accepted DATE NOT NULL
);

COMMENT ON COLUMN artwork.artwork_id IS
    'Artwork ID Number';

COMMENT ON COLUMN artwork.artist_id IS
    'Artist ID Number';

COMMENT ON COLUMN artwork.artwork_no IS
    'Artwork Number relative to individual Artist''s MAU Stock, 
     e.g. 1, 3, 11, 109';

COMMENT ON COLUMN artwork.artwork_title IS
    'Artwork Title';

COMMENT ON COLUMN artwork.artwork_date_accepted IS
    'Date Artwork was accepted by MAU';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( artwork_id );

ALTER TABLE artwork ADD CONSTRAINT artwork_nk UNIQUE ( artist_id,
                                                       artwork_no );

CREATE TABLE artwork_media (
    artmedia_id   NUMBER(3) NOT NULL,
    artmedia_name VARCHAR2(50 CHAR) NOT NULL
);

COMMENT ON COLUMN artwork_media.artmedia_id IS
    'Artwork Media Description ID Number';

COMMENT ON COLUMN artwork_media.artmedia_name IS
    'Artwork Media Description Name';

ALTER TABLE artwork_media ADD CONSTRAINT artwork_media_pk PRIMARY KEY ( artmedia_id )
;

CREATE TABLE artwork_status (
    art_status_id   NUMBER(7) NOT NULL,
    artwork_id      NUMBER(7) NOT NULL,
    art_status_date DATE NOT NULL,
    art_status_cat  CHAR(1 CHAR) NOT NULL,
    gallery_id      NUMBER(7)
);

ALTER TABLE artwork_status
    ADD CHECK ( art_status_cat IN ( 'G', 'R', 'S', 'T', 'W' ) );

COMMENT ON COLUMN artwork_status.art_status_id IS
    'Artwork Status ID Number';

COMMENT ON COLUMN artwork_status.artwork_id IS
    'Artwork ID Number';

COMMENT ON COLUMN artwork_status.art_status_date IS
    'Artwork Status Date';

COMMENT ON COLUMN artwork_status.art_status_cat IS
    'Artwork Status Category (1 Char),
     W: Warehouse (in MAU storage)
     T: Transit (to gallery)
     D: Display (at gallery)
     S: Sold
     R: Returned (to artist)';

COMMENT ON COLUMN artwork_status.gallery_id IS
    'Gallery ID Number';

ALTER TABLE artwork_status ADD CONSTRAINT artwork_status_pk PRIMARY KEY ( art_status_id
);

ALTER TABLE artwork_status
    ADD CONSTRAINT artwork_status_nk UNIQUE ( artwork_id,
                                              art_status_date,
                                              art_status_cat );

CREATE TABLE artwork_style (
    artstyle_id   NUMBER(3) NOT NULL,
    artstyle_name VARCHAR2(50 CHAR) NOT NULL
);

COMMENT ON COLUMN artwork_style.artstyle_id IS
    'Artwork Style ID Number';

COMMENT ON COLUMN artwork_style.artstyle_name IS
    'Artwork Style Name';

ALTER TABLE artwork_style ADD CONSTRAINT artwork_style_pk PRIMARY KEY ( artstyle_id )
;

CREATE TABLE customer (
    customer_id       NUMBER(7) NOT NULL,
    customer_givname  VARCHAR2(50 CHAR) NOT NULL,
    customer_famname  VARCHAR2(50 CHAR) NOT NULL,
    customer_phone    CHAR(10 CHAR) NOT NULL,
    customer_business VARCHAR2(100 CHAR),
    address_id        NUMBER(7) NOT NULL
);

COMMENT ON COLUMN customer.customer_id IS
    'Customer ID Number';

COMMENT ON COLUMN customer.customer_givname IS
    'Customer Given/First Name';

COMMENT ON COLUMN customer.customer_famname IS
    'Customer Family/Last Name';

COMMENT ON COLUMN customer.customer_phone IS
    'Customer Phone/Contact Number,
10 Numeric Chars Required';

COMMENT ON COLUMN customer.customer_business IS
    'Customer Business Name (optional)';

COMMENT ON COLUMN customer.address_id IS
    'Address ID Number';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE exhibit (
    exhibit_id           NUMBER(7) NOT NULL,
    gallery_id           NUMBER(7) NOT NULL,
    artwork_id           NUMBER(7) NOT NULL,
    exhibit_start_date   DATE NOT NULL,
    exhibit_end_date     DATE,
    exhibit_catalog_feat CHAR(1 CHAR) NOT NULL
);

ALTER TABLE exhibit
    ADD CHECK ( exhibit_catalog_feat IN ( 'N', 'Y' ) );

COMMENT ON COLUMN exhibit.exhibit_id IS
    'Exhibit ID Number';

COMMENT ON COLUMN exhibit.gallery_id IS
    'Gallery ID Number';

COMMENT ON COLUMN exhibit.artwork_id IS
    'Artwork ID Number';

COMMENT ON COLUMN exhibit.exhibit_start_date IS
    'Exhibit Start Date of an Artwork';

COMMENT ON COLUMN exhibit.exhibit_end_date IS
    'Exhibit End Date of an Artwork';

COMMENT ON COLUMN exhibit.exhibit_catalog_feat IS
    'Describes whether an Exhibited Artwork has been featured in a catalogue or not (Y/N)';

ALTER TABLE exhibit ADD CONSTRAINT exhibit_pk PRIMARY KEY ( exhibit_id );

ALTER TABLE exhibit
    ADD CONSTRAINT exhibit_nk UNIQUE ( gallery_id,
                                       artwork_id,
                                       exhibit_start_date );

CREATE TABLE gallery (
    gallery_id              NUMBER(7) NOT NULL,
    gallery_name            VARCHAR2(100 CHAR) NOT NULL,
    gallery_manager_givname VARCHAR2(50 CHAR) NOT NULL,
    gallery_manager_famname VARCHAR2(50 CHAR) NOT NULL,
    gallery_phone           CHAR(10 CHAR) NOT NULL,
    gallery_comm_percent    NUMBER(5, 2) NOT NULL,
    gallery_opentime        CHAR(5 CHAR) NOT NULL,
    gallery_closetime       CHAR(5 CHAR) NOT NULL,
    address_id              NUMBER(7) NOT NULL
);

COMMENT ON COLUMN gallery.gallery_id IS
    'Gallery ID Number';

COMMENT ON COLUMN gallery.gallery_name IS
    'Gallery Name';

COMMENT ON COLUMN gallery.gallery_manager_givname IS
    'Gallery Manager''s First/Given Name';

COMMENT ON COLUMN gallery.gallery_manager_famname IS
    'Gallery Manager''s Family/Last Name';

COMMENT ON COLUMN gallery.gallery_phone IS
    'Gallery''s Contact/Phone Number,
Requires 10 Numeric Chars';

COMMENT ON COLUMN gallery.gallery_comm_percent IS
    'Gallery Artwork-Sale Commission Percentage';

COMMENT ON COLUMN gallery.gallery_opentime IS
    'Gallery Opening Time in 24h Format (HH:MM),
     5 Chars Required: 4 numbers, 1 centered semicolon';

COMMENT ON COLUMN gallery.gallery_closetime IS
    'Gallery Closing Time in 24h Format (HH:MM),
     5 Chars Required: 4 numbers, 1 centered semicolon';

COMMENT ON COLUMN gallery.address_id IS
    'Address ID Number';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gallery_id );

CREATE TABLE sale (
    sale_id     NUMBER(7) NOT NULL,
    sale_date   DATE NOT NULL,
    sale_price  NUMBER(9, 2) NOT NULL,
    customer_id NUMBER(7) NOT NULL,
    exhibit_id  NUMBER(7) NOT NULL
);

COMMENT ON COLUMN sale.sale_id IS
    'Sale ID Number';

COMMENT ON COLUMN sale.sale_date IS
    'Date of Artwork''s Sale';

COMMENT ON COLUMN sale.sale_price IS
    'Sale Price of Artwork,
     Range: 0.00 ... 9,999,999.99 (Dollars.cents)';

COMMENT ON COLUMN sale.customer_id IS
    'Customer ID Number';

COMMENT ON COLUMN sale.exhibit_id IS
    'Exhibit ID Number';

CREATE UNIQUE INDEX sale__idx ON
    sale (
        exhibit_id
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

ALTER TABLE artist
    ADD CONSTRAINT address_artist FOREIGN KEY ( address_id )
        REFERENCES address ( address_id );

ALTER TABLE customer
    ADD CONSTRAINT address_customer FOREIGN KEY ( address_id )
        REFERENCES address ( address_id );

ALTER TABLE gallery
    ADD CONSTRAINT address_gallery FOREIGN KEY ( address_id )
        REFERENCES address ( address_id );

ALTER TABLE artist
    ADD CONSTRAINT artist_artist FOREIGN KEY ( artist_recommended_by )
        REFERENCES artist ( artist_id );

ALTER TABLE artwork
    ADD CONSTRAINT artist_artwork FOREIGN KEY ( artist_id )
        REFERENCES artist ( artist_id );

ALTER TABLE artmedia_art
    ADD CONSTRAINT artmedia_art_artwork_fk FOREIGN KEY ( artwork_id )
        REFERENCES artwork ( artwork_id );

ALTER TABLE artmedia_art
    ADD CONSTRAINT artmedia_art_artwork_media_fk FOREIGN KEY ( artmedia_id )
        REFERENCES artwork_media ( artmedia_id );

ALTER TABLE artstyle_art
    ADD CONSTRAINT artstyle_art_artwork_fk FOREIGN KEY ( artwork_id )
        REFERENCES artwork ( artwork_id );

ALTER TABLE artstyle_art
    ADD CONSTRAINT artstyle_art_artwork_style_fk FOREIGN KEY ( artstyle_id )
        REFERENCES artwork_style ( artstyle_id );

ALTER TABLE artwork_status
    ADD CONSTRAINT artwork_artstatus FOREIGN KEY ( artwork_id )
        REFERENCES artwork ( artwork_id );

ALTER TABLE exhibit
    ADD CONSTRAINT artwork_exhibit FOREIGN KEY ( artwork_id )
        REFERENCES artwork ( artwork_id );

ALTER TABLE sale
    ADD CONSTRAINT customer_sale FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE sale
    ADD CONSTRAINT exhibit_sale FOREIGN KEY ( exhibit_id )
        REFERENCES exhibit ( exhibit_id );

ALTER TABLE artwork_status
    ADD CONSTRAINT gallery_artstatus FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE exhibit
    ADD CONSTRAINT gallery_exhibit FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             1
-- ALTER TABLE                             33
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off